version: 0.2
phases:
  build:
    commands:
      - echo "BASE_REF=$CODEBUILD_WEBHOOK_BASE_REF"
      - echo "HEAD_REF=$CODEBUILD_WEBHOOK_HEAD_REF"
      - echo "Secondary branch before:" && cd $CODEBUILD_SRC_DIR_SECONDARY_SRC && git branch
      - BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_BASE_REF | sed 's|refs/heads/||')
      - cd $CODEBUILD_SRC_DIR_SECONDARY_SRC && git fetch origin $BRANCH_NAME && git checkout $BRANCH_NAME
      - echo "Secondary branch after:" && git branch
